import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const panelHtml = fs.readFileSync(path.resolve('thunderbird-addon/sidebar/panel.html'), 'utf8');
const panelJs = fs.readFileSync(path.resolve('thunderbird-addon/sidebar/panel.js'), 'utf8');
const panelCss = fs.readFileSync(path.resolve('thunderbird-addon/sidebar/panel.css'), 'utf8');

assert.match(panelJs, /new URLSearchParams\(window\.location\.search\)/, 'panel should read layout mode from query string');
assert.match(panelJs, /document\.body\.dataset\.layout\s*=\s*layoutMode/, 'panel should expose layout mode on body');
assert.match(panelJs, /const mailPaneToken = layoutParams\.get\(['"]mailpaneToken['"]\)/, 'panel should read a mailpane readiness token from query string');
assert.match(panelJs, /browser\.TbMailPane\.markPanelReady\(mailPaneToken\)/, 'panel should report when the embedded mailpane UI becomes ready');
assert.match(panelHtml, /class="toolbar-groups"/, 'mailpane toolbar should introduce an explicit grouped toolbar wrapper');
assert.match(panelHtml, /class="app-shell"/, 'mailpane panel should expose a stable app shell for container-based layout observation');
assert.match(panelHtml, /class="topbar toolbar-group toolbar-group-primary"/, 'primary actions should live in their own toolbar group');
assert.match(panelHtml, /class="taskbar toolbar-group toolbar-group-task"/, 'task actions should live in their own toolbar group');
assert.match(panelJs, /function isToolbarGroupWrapped\(group\)/, 'panel should detect whether a toolbar group has wrapped');
assert.match(panelJs, /group\.classList\.toggle\('toolbar-group--wrapped'/, 'panel should mark wrapped toolbar groups explicitly');
assert.match(panelJs, /group\.classList\.toggle\('toolbar-group--single'/, 'panel should mark single-line toolbar groups explicitly');
assert.doesNotMatch(panelJs, /message && message\.type === 'todo:force-layout-sync'/, 'panel should not keep the old explicit layout refresh message path');
assert.doesNotMatch(panelJs, /new ResizeObserver\(/, 'panel should no longer rely on a ResizeObserver for this refresh path');
assert.doesNotMatch(panelJs, /function connectMailpaneResizeObserver\(\)/, 'panel should not keep dedicated ResizeObserver wiring once explicit refresh is available');
assert.match(panelJs, /window\.addEventListener\('resize', scheduleMailpaneLayoutSync\)/, 'panel should resync toolbar layout on resize');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s*\{[\s\S]*min-width:\s*0;/, 'mailpane body must remove popup min-width');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s*\{[\s\S]*height:\s*100%;/, 'mailpane body must fill the embedded host height without forcing viewport geometry');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s*\{[\s\S]*width:\s*100%;/, 'mailpane body should fully occupy the embedded host width');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s*\{[\s\S]*--e2c-mailpane-toolbar-group-gap:\s*clamp\(/, 'mailpane should define a larger gap between toolbar groups');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s*\{[\s\S]*--e2c-mailpane-toolbar-row-gap:\s*clamp\(/, 'mailpane should define a smaller gap for wrapped rows within a group');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-groups\s*\{[\s\S]*display:\s*flex;/, 'mailpane toolbar wrapper should stack grouped rows explicitly');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-groups\s*\{[\s\S]*flex-direction:\s*column;/, 'mailpane toolbar wrapper should remain vertically grouped');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-groups\s*\{[\s\S]*gap:\s*var\(--e2c-mailpane-toolbar-group-gap\);/, 'mailpane toolbar wrapper should keep inter-group spacing distinct');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*\{[\s\S]*display:\s*flex;/, 'each toolbar group should manage its own internal wrapping');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*\{[\s\S]*flex-wrap:\s*wrap;/, 'each toolbar group should wrap internally when width runs out');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*\{[\s\S]*row-gap:\s*var\(--e2c-mailpane-toolbar-row-gap\);/, 'wrapped rows inside a group should use the tighter gap');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*\{[\s\S]*column-gap:\s*var\(--e2c-mailpane-control-gap\);/, 'toolbar groups should still shrink horizontal gaps before wrapping');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group--single\s*\{[\s\S]*justify-content:\s*center;/, 'single-line toolbar groups should stay centered');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group--wrapped\s*\{[\s\S]*justify-content:\s*flex-start;/, 'wrapped toolbar groups should realign to the left');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*>\s*button\s*\{[\s\S]*flex:\s*0\s+0\s+auto;/, 'mailpane toolbar buttons should keep content-driven widths');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*>\s*button\s*\{[\s\S]*white-space:\s*nowrap;/, 'mailpane toolbar buttons should keep labels on one line');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.toolbar-group\s*>\s*button\s*\{[\s\S]*padding-inline:\s*/, 'mailpane toolbar buttons should use content-sized inline padding');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.groups\s*\{[\s\S]*min-height:\s*0;/, 'mailpane groups area should absorb remaining height and stay scrollable');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.groups\s*\{[\s\S]*overflow:\s*auto;/, 'mailpane groups area should own the main scroll behavior');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.groups\s*\{[\s\S]*gap:\s*var\(--e2c-mailpane-group-gap\);/, 'mailpane groups area should compress internal vertical spacing as height shrinks');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.footer\s*\{[\s\S]*display:\s*grid;/, 'mailpane footer should remain a stable stacked tail section');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.footer\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\);/, 'mailpane footer should stack modules vertically in narrow widths');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.footer\s*\{[\s\S]*overflow:\s*hidden;/, 'mailpane footer should keep its visible region stable');
assert.match(panelCss, /body\[data-layout="mailpane"\]\s+\.imported-host\s*\{[\s\S]*overflow:\s*auto;/, 'mailpane imported section should scroll inside the footer instead of pushing it away');

console.log('mailpane layout tests passed');
